name: Update extensions
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Merge upstream
        run: |
          ./codelldb/update.sh
          ./update-vscode-plugins.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push changes
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          STATUS=$(git status -s)
          if [ -n "$STATUS" ]; then
              git add .
              git commit -m "[automatic] $(date) update extensions"
              git push origin master
          fi
